<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Finally Clause</title>
</head>
<body>
    <h1>Finally Clause</h1>
    <h2>Finally use for cleanups code it will run after getting error in try or catch block.</h2>

    <script>
       const f = () => {
        try{
            let a = 0;
            // console.log(program);
            console.log("Program ran successfully!!!");
            return
        }
        catch(err){
            console.log("This is Error: ",err);
            console.log(p);
        }
        finally{
            console.log("I am a good boy.");
            // close the file
            // exit from loop
            // write to the log file
        }
       }

       f();
       console.log("End");
       
    </script>
</body>
</html>